name: 'su_homework'
version: '1.0.0'
config-version: 2

profile: 'snowflake'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  su_homework:
    +required_tests: {".*": 3, "not_null": 1, "unique.|unique_*|unique*": 1}
    kpis:
      +required_tests: {".*": 0}
